[package]
name = "server-windows"
version = "0.1.0"
edition = "2021"

[workspace]
exclude = ["nvenc-rs", "webrtc-helper"]

[dependencies]
nvenc = { path = "nvenc-rs/nvenc" }
webrtc = "0.6"
webrtc-helper = { path = "webrtc-helper" }
log = "0.4.0"
env_logger = "0.10.0"
tokio = { version = "1.21.1", features = ["full"] }
bytes = "1.2.1"

[dependencies.windows]
version = "0.43"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_System_Performance",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging"
]
