[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Joseph Rafael Ferrer <rafael2x0@gmail.com>"]
license = "MIT OR Apache-2.0"

[workspace]
resolver = "2"
members = ["audio-capture", "audio-encoder", "conveyor-buffer", "input-injection"]
exclude = ["windows-reexport"]

[workspace.dependencies]
approx = "0.5.1"
bitflags = "2.4.1"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
windows = { package = "windows-reexport", path = "windows-reexport" } # version = "0.51.1"
