[package]
name = "client-android"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = "0.19"
ndk-sys = { version = "0.3", features = ["media"] }
anyhow = "1.0"
crossbeam-channel = "0.5"

