[package]
name = "audio-encoder"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]

[build-dependencies]
cmake = "0.1.50"
bindgen = "0.68.1"