[package]
name = "nvenc-sys"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.53"

[dependencies.windows]
version = "0.36"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader"
]
